# Include config file.
configfile: "config/config.yaml"


# Load in data rules.
include: "rules/common.smk"
include: "rules/data.smk"
include: "rules/eda.smk"


rule all:
    input:
        rules.data_all.input,
        rules.eda_all.input,
