paths:
  output_dir: "output"

twitch:
  paths:
    twitch_cred_file: ".env"
    emote_dir: "emotes"
    vod_chat_dir: "vod_chats"
  channel:
    - "Jerma985"
  type: "archive"
  format: "irc"

analysis:
  paths:
    plot_dir: "plots"
  # Ignore case when evaluating patterns.
  ignorecase: false

  # Interval of time to run analysis.
  # https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-offset-aliases
  interval: min

  frequency:
    patterns:
      omegalul: "OMEGALUL"
      plus2: "\\+2"
      minus2: "\\-2"

  emotes:
    channel: true
    bttv_global: true
    twitch_global: true
    additional:
      - EZ
      - MonkaW
      - Pog
      - Clap
      - OMEGALUL

  top_words:
    ignore_emotes: true

  # users:


  word_proportions:
    # Name of comparison.
    plus2minus2:
      numerator:
        - "+2"
        - "OMEGALUL"
      denominator:
        - "-2"
