paths:
  output_dir: "output"

twitch:
  paths:
    twitch_cred_file: ".env"
    emote_dir: "emotes"
    vod_chat_dir: "vod_chats"
  channel:
    - "Jerma985"
  type: "archive"
  format: "irc"

analysis:
  paths:
    plot_dir: "plots"

  # Ignore case when evaluating patterns.
  ignorecase: false

  # Interval of time to run analysis.
  # https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-offset-aliases
  interval: min

  frequency:
    patterns:
      omegalul: "OMEGALUL"
      plus2: "\\+2"
      minus2: "\\-2"

  emotes:
    bttv_channel:
      include_all: true
    twitch_channel:
      include_all: true
    bttv_global:
      include_all: false
      whitelist:
        - "LuL.png"
        - "monkaS.png"
        - "AngelThump.png"
        - "*Pride.png"
        - "D:.png"
    twitch_global:
      include_all: false
      whitelist:
        # <3 is original but non-alphanum characters removed.
        - "3.png"
        - "4Head.png"
        - "*Pride.png"
        - "BatChest.png"
        - "PogChamp.png"
        - "BibleThump.png"
        - "ResidentSleeper.png"
        - "Kappa*.png"
        - "KomodoHype.png"
        - "Kreygasm.png"
        - "LUL.png"
        - "NotLikeThis.png"
        - "Squid*.png"
        - "Vote*.png"

  top_words:
    ignore_emotes: true

  # users:
  # words_per_interval
