paths:
  output_dir: "output"

twitch:
  paths:
    twitch_cred_file: ".env"
    emote_dir: "emotes"
    vod_chat_dir: "vod_chats"

  channel:
    - "Jerma985"

  sort:
    by: "published_at"
    desc: true

  vod:
    type: "archive"
    top_n: null

analysis:
  paths:
    plot_dir: "plots"

  # Ignore case when evaluating patterns.
  ignorecase: false

  # Interval of time to run analysis.
  # https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-offset-aliases
  interval: min

  frequency:
    patterns:
      omegalul: "OMEGALUL"
      plus2: "\\+2"
      minus2: "\\-2"
      ohno: "D:|monkaW|monkaS"

  emotes:
    bttv_channel:
      include_all: true
    twitch_channel:
      include_all: true
    bttv_global:
      include_all: true
      # whitelist:
    twitch_global:
      include_all: true

  top_words:
    ignore_emotes: true

  # users:
  # words_per_interval
